name: Go Test and Coverage

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Run Go Tests & Upload Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.txt
